# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]
  included_files = ["*.wasm"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_IS_NETLIFY = "true"
  NODE_OPTIONS = "--max-old-space-size=2048"  # Increase Node memory for builds

# Increase function timeout for database operations
[functions.daily]
  memory = 1024
  timeout = 30